name: Run Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Jenkinsfile Runner
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0
        with:
          jenkinsfile: Jenkinsfile
          plugins: plugins.txt
