name: Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Jenkinsfile Runner
        uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
